/**
 * 分享来源识别规则默认值（与 src/js/config.js 的 Default_Config.Shares.SourceType 一致，由脚本提取生成）
 *
 * 注意：匹配按数组顺序从上到下进行，命中第一条即返回，因此越具体的规则必须排在越前面
 * （例如 zone.qq.com/secret 必须排在 qzone.qq.com 之前，否则永远命中不到）。
 */
export interface ShareSource {
    name: string;
    regulars: string;
}

export const SHARE_SOURCE_DEFAULTS: ShareSource[] = [
    { name: "QQ空间秘密", regulars: "zone.qq.com/secret" },
    { name: "手机QQ空间", regulars: "mobile.qzone.qq.com" },
    { name: "QQ空间", regulars: "qzone.qq.com" },
    { name: "QQ音乐", regulars: "y.qq.com" },
    { name: "QQ音乐", regulars: "i.y.qq.com" },
    { name: "QQ音乐", regulars: "music.qq.com" },
    { name: "网易云音乐", regulars: "music.163.com" },
    { name: "网易云音乐", regulars: "y.music.163.com" },
    { name: "酷狗音乐", regulars: "kugou.com" },
    { name: "酷狗音乐", regulars: "m.kugou.com" },
    { name: "酷狗音乐", regulars: "t1.kugou.com" },
    { name: "全民K歌", regulars: "kg.qq.com" },
    { name: "全民K歌", regulars: "kg2.qq.com" },
    { name: "匿问我答", regulars: "ti.qq.com" },
    { name: "微信公众号", regulars: "mp.weixin.qq.com" },
    { name: "天天爱消除", regulars: "peng.qq.com" },
    { name: "QQ手游中心", regulars: "gamecenter.qq.com" },
    { name: "QQ手游中心", regulars: "youxi.vip.qq.com" },
    { name: "知乎", regulars: "zhihu.com" },
    { name: "知乎", regulars: "m.zhihu.com" },
    { name: "新浪微博", regulars: "weibo.com" },
    { name: "新浪微博", regulars: "m.weibo.cn" },
    { name: "腾讯看点", regulars: "post.mp.qq.com" },
    { name: "腾讯视频", regulars: "v.qq.com" },
    { name: "腾讯视频", regulars: "m.v.qq.com" },
    { name: "QQ小程序-腾讯视频", regulars: "mqqapi://microapp/open\\?mini_appid=1109840991" },
    { name: "QQ小程序", regulars: "mqqapi://microapp" },
    { name: "易企秀", regulars: "i.eqxiu.com" },
    { name: "爱奇艺", regulars: "iqiyi.com" },
    { name: "爱奇艺", regulars: "www.iqiyi.com" },
    { name: "爱奇艺", regulars: "m.iqiyi.com" },
    { name: "IT之家", regulars: "m.ithome.com" },
    { name: "IT之家", regulars: "www.ithome.com" },
    { name: "中国联通", regulars: "10010.com" },
    { name: "中国联通", regulars: "m.10010.com" },
    { name: "芒果TV", regulars: "mgtv.com" },
    { name: "芒果TV", regulars: "m.mgtv.com" },
    { name: "乐视TV", regulars: "letv.com" },
    { name: "乐视TV", regulars: "m.letv.com" },
    { name: "一点资讯", regulars: "yidianzixun.com" },
    { name: "哔哩哔哩", regulars: "bilibili.com" },
    { name: "百度贴吧", regulars: "tieba.baidu.com" },
    { name: "水滴筹", regulars: "shuidichou.com" },
    { name: "Reddit", regulars: "reddit.com" },
    { name: "GitHub", regulars: "github.com" },
    { name: "抖音", regulars: "douyin.com" },
    { name: "今日头条", regulars: "toutiao.com" },
    { name: "今日头条", regulars: "toutiao.org" },
    { name: "酷我音乐", regulars: "kuwo.cn" },
    { name: "火锅视频", regulars: "yoo.qq.com" },
    { name: "全民小视频", regulars: "quanmin.baidu.com" },
    { name: "王者荣耀", regulars: "svp.tencent-cloud.com" },
    { name: "王者荣耀", regulars: "qt.qq.com" },
    { name: "QQ飞车手游", regulars: "speedm.qq.com" },
    { name: "QQ飞车", regulars: "speed.qq.com" },
    { name: "QQ飞车", regulars: "speed.qq.com" },
    { name: "英雄联盟", regulars: "lol.qq.com" },
    { name: "看点快报", regulars: "kuaibao.qq.com" },
    { name: "腾讯新闻", regulars: "news.qq.com" },
    { name: "51CTO 学院", regulars: "edu.51cto.com" },
    { name: "轻松筹", regulars: "qschou.com" },
    { name: "搜狐视频", regulars: "tv.sohu.com" },
];
